version: "3"
services:
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/usr/src/app"
  backend:
    build: backend/
    ports:
      - "3001:3000"
    volumes:
      - "./backend:/usr/src/app"
      - "files:/root/.config/upload-scheduler"
  db:
    image: mongo
    volumes:
      - "db_volume:/data/db"
    ports:
      - "3003:27017"
volumes:
  files:
  db_volume:
