version: "3"
services:
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/usr/src/app"
  backend:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ".:/usr/src/app"
      - "files:/root/.config/upload-scheduler"
volumes:
  files:
  db_volume: